# Generated by Django 5.2 on 2025-05-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('First', 'First Year'), ('Second', 'الفرقة الثانية'), ('Third', 'الفرقة الثالثة'), ('Fourth', 'الفرقة الرابعة')], max_length=6),
        ),
    ]
