# Generated by Django 5.2 on 2025-05-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_structure_student_structure'),
        ('courses', '0002_alter_course_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=6),
        ),
    ]
