# Generated by Django 5.2 on 2025-05-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstructure',
            name='semester',
            field=models.CharField(choices=[('First', 'الترم الأول'), ('Second', 'الترم الثاني')], max_length=6),
        ),
        migrations.AlterField(
            model_name='studentstructure',
            name='year',
            field=models.CharField(choices=[('First', 'الفرقة الأولى'), ('Second', 'الفرقة الثانية'), ('Third', 'الفرقة الثالثة'), ('Fourth', 'الفرقة الرابعة')], max_length=6),
        ),
    ]
