# Generated by Django 5.2 on 2025-05-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_studentstructure_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstructure',
            name='year',
            field=models.CharField(choices=[('First', 'First Year'), ('Second', 'الفرقة الثانية'), ('Third', 'الفرقة الثالثة'), ('Fourth', 'الفرقة الرابعة')], max_length=6),
        ),
    ]
