# Generated by Django 5.2 on 2025-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_studentstructure_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstructure',
            name='semester',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=6),
        ),
        migrations.AlterField(
            model_name='studentstructure',
            name='year',
            field=models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year'), ('Fourth', 'Fourth Year')], max_length=6),
        ),
    ]
