# Generated by Django 5.2 on 2025-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
