# Generated by Django 5.2 on 2025-05-10 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrcodesession_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodesession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
